### PR TITLE
error 

### PR DESCRIPTION
**Pull request by Timmy5314**

### CODE REVIEW

**Comment by xrtw** [comment]
what the...

**Comment by Bland-1** [comment]
When goin to my private garage I spawn under water where can I get the garage interiors?

**Comment by CsakEgyWariiii** [comment]
Engine starting error. It only starts when I get out and then get in, and not always.

**Comment by xrtw** [comment]
> Engine starting error. It only starts when I get out and then get in, and not always.

you do not have keys. disable Config.ox_inventory if not using it

**Comment by Pilotodev** [comment]
The same thing happens to me, I have deactivated the ox inventory option, but when I enter a car that is not mine, the car does not start.

**Comment by CsakEgyWariiii** [comment]
https://streamable.com/96p43z Air garage not showing the list

**Comment by Pilotodev** [comment]
> > Engine starting error. It only starts when I get out and then get in, and not always.
> 
> you do not have keys. disable Config.ox_inventory if not using it

-------------------------------------------------
Can u help me pls?

**Comment by Joshua900** [comment]
hey so i cleared my database, and now when i spawn cars its says i down own the vehicle even tho i just bought it and stored it in the garage its somthing to do with keys but i cant figure it out

**Pull request closed without merging**
