### PR TITLE
tweak(client): images alignment in menus , and compatibility with lat…

### PR DESCRIPTION
**Pull request by renzuzu**
…est contextmenu

### CODE REVIEW

**Comment by vankhoa1** [comment]
Hello friend, I am very satisfied with your garage write, but I can't store the car with ParkButton E, I tried but can't put the car in the garage. can you guide me to fix it? I use ESX.

**Comment by vankhoa1** [comment]
Hi, here is my video can't use E key to access garage. 
https://www.youtube.com/watch?v=LxMPiCWRTic

**Comment by vankhoa1** [comment]
[MySQL] [ERROR] [renzu_garage] An error happens for query "SELECT" * FROM owned_vehicles WHERE isparked = 1 : []": ER_BAD_FIELD_ERROR: Unknow column "isparked" in "where clause"

**Comment by renzuzu** [comment]
add all required sql columns

and start renzu_popui its a dependency

**Comment by vankhoa1** [comment]
i installed it and it still doesn't work, i use fw esx

**Comment by vankhoa1** [comment]
can you give me discord id? i send info vps to you.

**Comment by vankhoa1** [comment]
Hello, I installed and the resources are running but when I check the garage locations, it doesn't show E to access the garage. I installed SQL
image

**Comment by renzuzu** [comment]
are you still having probllem?

open a new github issue not here, i am not monitoring this thread.

i suggest tot download all dependecies again and new garage version

**Pull request merged**
